apiVersion: v2
name: producer
description: High-throughput RabbitMQ producer for load testing
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x